// Central map of design assets exported from the Figma file (public/figma/*).
// Names follow the component they belong to in the design.

export const ICONS = {
  // top bar — the brand mark is NOT here: the Figma clone's teal glyph was
  // Monday's own logo and was removed; TopBar renders the NexProp wordmark
  search: "/figma/imgVariant9.svg",
  bell: "/figma/imgVariant10.svg",
  inbox: "/figma/imgVariant11.svg",
  invite: "/figma/imgVariant12.svg",
  marketplace: "/figma/imgVariant13.svg",
  settings: "/figma/imgVariant14.svg",
  help: "/figma/imgVariant15.svg",
  appsGrid: "/figma/imgGroup1.svg",
  avatar: "/figma/imgAmirShamsipur.png",

  // icon rail
  railHome: "/figma/imgVariant18.svg",
  railCrm: "/figma/imgVariant20.svg",
  railSidekick: "/figma/imgVariant22.svg",
  railAgents: "/figma/imgVariant24.svg",
  railTools: "/figma/imgVariant26.svg",
  railNotetaker: "/figma/imgVariant28.svg",
  railMore: "/figma/imgVariant30.svg",

  // home page
  add: "/figma/imgIconBasicAdd.svg",
  customize: "/figma/imgVariant32.svg",
  widgetPipeline: "/figma/imgVariant34.svg",
  filterAll: "/figma/imgVariant35.svg",
  filterDeals: "/figma/imgVariant36.svg",
  expand: "/figma/imgVariant37.svg",
  info: "/figma/imgVariant38.svg",
  widgetMeetings: "/figma/imgVariant41.svg",
  widgetRecent: "/figma/imgVariant43.svg",
  chevronLeft: "/figma/imgVariant44.svg",
  chevronRight: "/figma/imgVariant45.svg",
  star: "/figma/imgVariant47.svg",
  boardLeads: "/figma/imgVariant46.svg",
  boardDeals: "/figma/imgVariant48.svg",
  boardContacts: "/figma/imgVariant50.svg",
  boardActivities: "/figma/imgVariant52.svg",
  boardDashboard: "/figma/imgVariant54.svg",
  googleLogo: "/figma/imgGoogleLogo.png",
  outlookLogo: "/figma/imgOutlookLogo.png",
  calendarPreview: "/figma/imgCalendarConnectionPreview.png",

  // announcement banner
  aiLogo1: "/figma/ban_imgVector2.png",
  aiLogo2: "/figma/ban_imgVector3.png",
  aiLogo3: "/figma/ban_imgVector4.png",
  aiLogo4: "/figma/ban_imgVector5.png",
  aiLogoRing: "/figma/ban_imgVector.svg",
  aiLogoRingInner: "/figma/ban_imgVector1.svg",
  bannerClose: "/figma/ban_imgVariant5.svg",

  // workspace sidebar
  wsDots: "/figma/ws_imgVariant31.svg",
  wsSearch: "/figma/ws_imgVariant32.svg",
  wsCollapse: "/figma/ws_imgVariant33.svg",
  wsChevron: "/figma/ws_imgVariant34.svg",
  wsAdd: "/figma/ws_imgIconBasicAdd.svg",
  wsAgentsChevron: "/figma/ws_imgVariant37.svg",
  wsContentChevron: "/figma/ws_imgVariant38.svg",
  navHome: "/figma/ws_imgVariant39.svg",
  navContacts: "/figma/ws_imgVariant40.svg",
  navDeals: "/figma/ws_imgVariant41.svg",
  navLeads: "/figma/ws_imgVariant42.svg",
  navAccounts: "/figma/ws_imgVariant43.svg",
  navProjects: "/figma/ws_imgVariant44.svg",
  navProducts: "/figma/ws_imgVariant45.svg",
  navActivities: "/figma/ws_imgVariant46.svg",
  navDashboard: "/figma/ws_imgVariant47.svg",
  syncCheck: "/figma/ws_imgVariant48.svg",
  syncChevron: "/figma/ws_imgVector.svg",
  syncClose: "/figma/ws_imgVariant49.svg",
  syncActivities: "/figma/ws_imgVariant52.svg",

  // workspace header
  hdrHomeBadge: "/figma/ws_hdr_imgVariant84.svg",
  hdrEdit: "/figma/ws_hdr_imgVariant86.svg",
  hdrFeedback: "/figma/ws_hdr_imgVariant87.svg",
  hdrAgents: "/figma/ws_hdr_imgVariant88.svg",
  hdrDots: "/figma/ws_hdr_imgVariant89.svg",

  // workspace tabs + content table
  tabRecents: "/figma/ws_tab_imgVariant53.svg",
  tabContent: "/figma/ws_tab_imgVariant54.svg",
  tabCollaborators: "/figma/ws_tab_imgVariant55.svg",
  tabPermissions: "/figma/ws_tab_imgVariant56.svg",
  tblSearch: "/figma/ws_tab_imgVariant57.svg",
  tblFilters: "/figma/ws_tab_imgVariant58.svg",
  tblCheckCircle: "/figma/ws_tab_imgVariant59.svg",
  tblSparkle: "/figma/ws_tab_imgVariant60.svg",
  tblInfoSmall: "/figma/ws_tab_imgVariant61.svg",
  tblInfo: "/figma/ws_tab_imgVariant62.svg",
  tblAiSummary: "/figma/ws_tab_imgVariant68.svg",
  rowProducts: "/figma/ws_tab_imgVariant69.svg",
  rowProjects: "/figma/ws_tab_imgVariant71.svg",
  rowActivities: "/figma/ws_tab_imgVariant73.svg",
  rowLeads: "/figma/ws_tab_imgVariant75.svg",
  rowContacts: "/figma/ws_tab_imgVariant77.svg",
  rowDeals: "/figma/ws_tab_imgVariant79.svg",
  rowAccounts: "/figma/ws_tab_imgVariant81.svg",
  rowDashboard: "/figma/ws_tab_imgVariant83.svg",

  // AI floaty
  floatySparkle: "/figma/floaty_sparkle.svg",

  // leads board — header
  bhTitleChevron: "/figma/lb_imgVariant54.svg",
  bhAiChevron: "/figma/lb_imgVariant55.svg",
  bhImport: "/figma/lb_imgVariant56.svg",
  bhIntegrate: "/figma/lb_imgVariant57.svg",
  bhAutomate: "/figma/lb_imgVariant58.svg",
  bhAgents: "/figma/lb_imgVariant59.svg",
  bhChat: "/figma/lb_imgVariant60.svg",
  bhLink: "/figma/lb_imgVariant61.svg",
  bhDots: "/figma/lb_imgVariant62.svg",
  bhPerson: "/figma/lb_imgVariant63.svg",
  bhFilter: "/figma/bh_filter_thin.svg",
  bhGroupBy: "/figma/lb_imgVariant65.svg",
  bhMore: "/figma/lb_imgVariant66.svg",
  bhCollapse: "/figma/lb_imgVariant67.svg",
  bhTabDots: "/figma/lb_imgVariant3.svg",
  bhTabAdd: "/figma/lb_imgVariant4.svg",
  bhNewLeadCaret: "/figma/lb_imgVariant5.svg",
  bhSearch: "/figma/bh_search_thin.svg",
  bhFilterCaret: "/figma/lb_imgVariant7.svg",
  aiAgentAvatar1: "/figma/lb_imgAgents1.png",
  aiAgentAvatar2: "/figma/lb_imgAgents2.png",

  // leads board — content
  grpChevron: "/figma/lbt_imgVariant1.svg",
  grpAdd: "/figma/lbt_imgIconBasicAdd2.svg",
  tlAdd: "/figma/lbt_imgIconBasicAdd.svg",
  tlHeader: "/figma/lbt_imgVariant73.svg",
  rowOpen: "/figma/lbt_imgVariant69.svg",
  rowDots: "/figma/lbt_imgVariant8.svg",
} as const;

export type IconName = keyof typeof ICONS;
